### ISSUE TITLE
Get patches and plot

### ISSUE THREAD

**Issue by ghost** [chathika/NL4Py#10]
I've just checked the arxiv document, and the YouTube video. Is it possible to get and plot NetLogo patches via this package (like it was in RNetLogo by NLGetPatches)?

**Comment by chathika** [comment]
@ewirth yes, you can export the patches view using: `nl4py.NetLogoHeadlessWorkspace.exportView(str image_name.png)` . For example:

```
n = nl4py.newNetLogoHeadlessWorkspace()
n.openModel("MyModel.nlogo")
n.command("setup")
n.exportView("patches.png")
```
