### ISSUE TITLE
BuildServer.bat not generic

### ISSUE THREAD

**Issue by brandon-fsu** [chathika/NL4Py#3]
The batch file for building the server has your Windows user name in the path, and therefor will not run on anybody's machine. You're also using a linux command - cp - in it, so anyone that doesn't have cygwin or another linux emulator set as their default batch executor will fail.

**Comment by chathika** [comment]
For typical use the python package can simply be installed with `pip install nl4py`. However, if you wanted to make changes to the `nl4py` source code you would want to execute the commands in the batch file. 

I've made a more generic version of the build script here:  [https://github.com/chathika/NL4Py/blob/master/BuildServer.sh](https://github.com/chathika/NL4Py/blob/master/BuildServer.sh )

Hope this helps.
